### ISSUE TITLE
$Format:%d$ causes unreproducible builds

### ISSUE THREAD

**Issue by bobby285271** [fsspec/gcsfs#441]
Hi, we packaged this in Nixpkgs and many thanks for making this available.

Recently we found that in `_version.py`, there is:

https://github.com/fsspec/gcsfs/blob/85e2ee2abfa429f3c10cc08dcda8ed30db8ab3b5/gcsfs/_version.py#L21-L25

This makes https://github.com/fsspec/gcsfs/archive/refs/tags/2021.11.1.tar.gz no longer immutable as soon as development continues, `git_refnames` will change from for example `" (HEAD -> main, tag: 2021.10.1)"` to `" (tag: 2021.10.1)"`. We noticed this in https://github.com/NixOS/nixpkgs/pull/153553#issuecomment-1005713811. It will be really nice if we can get rid of this so we can make sure the tarball we fetch has a fixed sha256.

**Comment by jonringer** [comment]
For motivation, please take  a look at https://reproducible-builds.org/

**Comment by martindurant** [comment]
I am aware that versioneer within this repo is out of date. Does updating it fix the problem? 

I don't exactly follow what the issue is though: you would only ever install tagged commits, which are the same as releases on pypi or conda. If you were to release with a version that is not a tag, you would get version strings like "2021.11.1+9.g556a852", both for the `__version__` and generated file names.

**Comment by jonringer** [comment]
> I don't exactly follow what the issue is though:

The issue is that all refnames are captured, including `main`.

So when you fetch tarball immediately after release, you get additional content about references such as `main`.

If you were to check out the repository after main has progressed, then the refnames will omit `main`.

Now the contents of gcsfs is a combination of code and time. We would just like for it to be code.

**Comment by martindurant** [comment]
OK, I see, sort of.

I must admit that installing from github is not normal practice for packaging in my pydata worls, and I have not heard of this thing before. versioneer is included in the repo, but not code we contributed as such - it is installed by the [versioneer tool](https://github.com/python-versioneer/python-versioneer). Many of the packages I work on operate the same way. Perhaps it would be worth noting an issue with them, and they would have a suggestion for best practice. 

Do you have a specific suggestion of what you would like to see done?

**Comment by jonringer** [comment]
I would use `%(describe)` instead. Refnames seems to be a nice-to-have when you already expose the commit which is can pinpoint where.

**Comment by jonringer** [comment]
Likely also related: https://github.com/NixOS/nixpkgs/pull/153557

**Comment by martindurant** [comment]
Have you had a chance to ask any versioneer or other repos that must be facing the same thing?

**Comment by jonringer** [comment]
It's just leveraging git format conventions, so I think it's intended that you could capture multiple references.

I just don't think the intended use case was for tarballs.

**Comment by martindurant** [comment]
Perhaps you could propose a concrete PR, because I'm afraid I am still non the wiser here.

**Comment by jonringer** [comment]
Ah, I see, the versioneer.py is just created from the versioneer toolchain. So even though it's commited to your repo, it's not really your domain.

**Comment by martindurant** [comment]
>  it's not really your domain.

Exactly

**Comment by jonringer** [comment]
There's already an upstream issue here: https://github.com/python-versioneer/python-versioneer/issues/217
