### ISSUE TITLE
_put_file does not allow to specify content encoding

### ISSUE THREAD

**Issue by racinmat** [fsspec/gcsfs#543]
In order to utilize the [decompressive transcoding](https://cloud.google.com/storage/docs/transcoding) of GCS, I need to set the `content_encoding`. But the `_put_file` does not allow to set it. It allows to set `metadata`, but underneath it calls `simple_upload`, where the `content_encoding` must be set in `fixed_key_metadata` optional argument, and this is not exposed to the `_put_file`, so there is no way to set it.

**Comment by martindurant** [comment]
Is there a reason not to simply gzip the file yourself?

**Comment by racinmat** [comment]
I gzipped it myself, but the content_encoding is not set properly.
I gzipped and uploaded the file using:
```python
        with tempfile.TemporaryDirectory() as tmpdirname:
            local_name = f'{tmpdirname}/{resp["identifier"]}.json.gz'
            with gzip.open(local_name, mode='wb') as f:
                f.write(await response.read())
            await fs.filesystem._put_file(local_name, file_path, content_type='application/json')
```
but if I don't set the content encoding, the decompressive transcoding does not work, and when I inspect the metadata in GCS, the object does not have the contect_encoding set.

**Comment by martindurant** [comment]
I think similar things have come up elsewhere. While I agree in principle that we should be passing on all the headers you intend for GCS to see, I still don't really see the need for this "transcoding" when you can easily wrap both the read and write with gzip. The MIME type would then be xapp/gzip instead (or even octet-stream), which is fine. Since we nearly always expect the read following a write to also occur in python, and nothing ever checks these headers, it makes no difference when staying within our own ecosystem.

An additional wrinkle to consider, and this issue has definitely bitten us. When you have a content encoding set like this, the file size reported is not the same as the actual number of bytes you receive, and range requests will not work.

**Comment by racinmat** [comment]
I understand, I know the reported size does not fit then. In my case the consecutive reads do not happen through the library and I want to use this feature of decompressive transcoding. I think it's neat and it's sad that this library does not support it.
